import type { Metadata } from "next";
import Link from "next/link";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { after } from "next/server";

import {
  QuoteDocument,
  quoteFileName,
  type QuoteDocumentData,
} from "@/components/quote-document";
import { SavePdfButton } from "@/components/save-pdf-button";
import { clientIpFromHeaders, isLinkPreviewBot } from "@/lib/bots";
import { formatDateTime } from "@/lib/format";
import { normalizeIsraeliPhone } from "@/lib/phone";
import {
  isRevokedToken,
  loadPublicQuote,
  recordQuoteView,
} from "@/lib/public-quote";

import { QuoteDecision } from "./quote-decision";
import { RevokedQuote } from "./revoked";

export async function generateMetadata({
  params,
}: PageProps<"/q/[public_token]">): Promise<Metadata> {
  const { public_token } = await params;
  const quote = await loadPublicQuote(public_token);

  /*
   * A price quote has no business being indexed by a search engine, and this
   * is the single most important line in the file. Both branches carry it,
   * including the not-found branch: getting a quote into Google is a privacy
   * leak far worse than any preview card is worth.
   */
  const robots = { index: false, follow: false };

  if (!quote) {
    return { title: "הצעת מחיר", robots };
  }

  /* The subject first: in a phone's tab strip, the business name is the part
     that can afford to be truncated. */
  const title = quote.title
    ? `${quote.title} — הצעת מחיר מ${quote.business.name}`
    : `הצעת מחיר מ${quote.business.name}`;
  // The amount is deliberately left out of the preview: these links get pasted
  // into group chats, and the price should only appear once the page is
  // actually opened. The generated card follows the same rule.
  const description = "לחצו לצפייה בפירוט המלא ולאישור ההצעה.";

  return {
    title,
    description,
    robots,
    /*
     * WhatsApp is the entire distribution model for this product, and it reads
     * og: tags — not the title and description above. Without these the client
     * receives a bare URL, which reads as spam from a number they may not have
     * saved.
     *
     * The image itself is generated by the colocated opengraph-image route;
     * Next appends the og:image tags for it automatically, so listing it here
     * would only risk the two disagreeing.
     */
    openGraph: {
      type: "website",
      locale: "he_IL",
      siteName: "תמחורולוג",
      title,
      description,
    },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default async function PublicQuotePage({
  params,
}: PageProps<"/q/[public_token]">) {
  const { public_token } = await params;
  const quote = await loadPublicQuote(public_token);

  if (!quote) {
    // A link the owner retired by editing, rather than one that never existed.
    if (await isRevokedToken(public_token)) return <RevokedQuote />;
    notFound();
  }

  const requestHeaders = await headers();
  const userAgent = requestHeaders.get("user-agent");

  // Crawlers still get the page so the WhatsApp preview renders, but their
  // fetch must never count as the client opening the quote.
  if (!isLinkPreviewBot(userAgent)) {
    const ip = clientIpFromHeaders(requestHeaders);
    after(() => recordQuoteView(public_token, ip, userAgent));
  }

  const businessPhone = quote.business.phone
    ? normalizeIsraeliPhone(quote.business.phone)
    : null;

  // Once a client has decided, the buttons are gone for good. The final state
  // is shown instead, so a revisit cannot un-approve anything.
  //
  // "draft" is absent deliberately, and not only because loadPublicQuote no
  // longer returns one: this list is the answer to "may this person approve",
  // and an unsent quote is not something to approve.
  const isOpen = quote.status === "sent" || quote.status === "viewed";

  /* Numbers arrive from PostgREST as strings. Parsed once, here, so the
     document component deals in numbers and nothing downstream re-parses. */
  const document: QuoteDocumentData = {
    quoteNumber: quote.quoteNumber,
    title: quote.title,
    issuedAt: quote.issuedAt,
    validUntil: quote.validUntil,
    notes: quote.notes,
    subtotal: Number(quote.subtotal),
    taxAmount: Number(quote.taxAmount ?? 0),
    vatRate: Number(quote.vatRate),
    total: Number(quote.total),
    clientName: quote.clientName,
    business: quote.business,
    items: quote.items.map((item) => ({
      id: item.id,
      description: item.description,
      quantity: Number(item.quantity),
      unitPrice: Number(item.unitPrice),
      lineTotal: Number(item.lineTotal),
    })),
  };

  return (
    /*
      This is the one screen a client sees, and it is a document rather than an
      application. It grows from a phone's full width to a reading measure and
      then stops: max-w-document is 640px, and the page background carries the
      rest of the window. Widening it further would only make the totals travel
      away from the descriptions they belong to.

      More air above and below on a larger screen, so the document sits on the
      page instead of being pinned to the top of the window.
    */
    <main id="main" tabIndex={-1} className="mx-auto flex w-full max-w-document flex-1 flex-col gap-4 px-4 py-6 md:gap-5 md:py-12">
      {quote.status === "approved" ? (
        /*
          A status message, not a document heading. It was an h2, and because it
          sits above the quote card it announced itself before the page's only
          h1, which leaves a screen reader navigating by heading to meet a level
          two before a level one. role="status" is also the accurate description
          of what this banner is.
        */
        <section
          role="status"
          className="rounded-card border border-success/30 bg-success-soft p-5"
        >
          <p className="text-xl font-bold text-success">ההצעה אושרה</p>
          <p className="mt-1 text-sm leading-relaxed">
            תודה! {quote.business.name} ייצור איתך קשר בקרוב.
          </p>
          {quote.decisionName && quote.decidedAt ? (
            <p className="mt-2 text-xs text-muted">
              אושר על ידי{" "}
              <span className="font-semibold text-foreground">
                {quote.decisionName}
              </span>{" "}
              בתאריך{" "}
              <span className="numeric">{formatDateTime(quote.decidedAt)}</span>
            </p>
          ) : null}
        </section>
      ) : null}

      {quote.status === "declined" ? (
        <section
          role="status"
          className="rounded-card border border-border bg-background p-5"
        >
          <p className="text-xl font-bold">תודה על התשובה</p>
          <p className="mt-1 text-sm leading-relaxed text-muted">
            נרשם אצלנו שההצעה אינה רלוונטית. אם תשנה/י את דעתך, אפשר לפנות ישירות
            ל{quote.business.name}.
          </p>
        </section>
      ) : null}

      <QuoteDocument quote={document} />

      {isOpen ? (
        <QuoteDecision
          token={public_token}
          businessName={quote.business.name}
        />
      ) : null}

      {/*
        Some clients want a file, not a link — a building committee, a company,
        an accountant. This is that, without leaving the page they are already
        on and without asking them to install anything.
      */}
      <SavePdfButton fileName={quoteFileName(document)} />

      {businessPhone ? (
        <a
          href={`tel:${businessPhone.e164}`}
          className="print-hide inline-flex h-control w-full items-center justify-center rounded-control border border-border bg-surface text-base font-semibold transition-colors hover:bg-background"
        >
          יש שאלה? חייגו ל{quote.business.name}
        </a>
      ) : null}

      {/*
        A footer landmark rather than a loose paragraph: it was the one piece of
        this page with no semantic home, which left a screen reader no way to
        jump to it or past it.

        The name is also the only mention of the product a client ever sees, so
        it links home.
      */}
      <footer className="pt-2 text-center text-xs text-muted">
        נשלח באמצעות{" "}
        <Link
          href="/"
          // Nothing on this page should spend the client's data on a page they
          // have not asked for, and almost none of them will follow this.
          prefetch={false}
          className="font-semibold text-brand hover:underline"
        >
          תמחורולוג
        </Link>
        {" · "}
        {/*
          The statement has to be reachable without the floating button — the
          button is gone on paper, and a link is what a screen reader finds by
          walking the page.
        */}
        <Link
          href="/accessibility"
          prefetch={false}
          className="font-semibold text-brand hover:underline"
        >
          הצהרת נגישות
        </Link>
      </footer>
    </main>
  );
}
